# match what root_base was built against
c_stdlib_version:    # [osx]
  - 11.0             # [osx]

# unpin the compiler when cross compiling on macOS,
# since root_base effectively constrains the major version on its own
c_compiler_version:    # [osx and arm64]
  - "*"                # [osx and arm64]
cxx_compiler_version:  # [osx and arm64]
  - "*"                # [osx and arm64]
