{% set name = "gwollum" %}
{% set version = "4.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.ligo.org/virgo/virgoapp/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2cd42b68703e7e76299cd81baab57bb20216996721c8d1b62437fb1b57dca74d
  patches:
    # fix rootcling when cross-compiling
    - rootcling-cross.patch  # [osx and arm64]

build:
  error_overdepending: true
  error_overlinking: true
  number: 2
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("gwollum", max_pin="x") }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake >=3.12.0
    - make  # [unix]
    - pkg-config  # [unix]
    # when cross-compiling, need rootcling from build_platform
    - root_base  # [osx and arm64]
  host:
    - fftw
    - hdf5
    - libframel 8.42
    - root_base

test:
  requires:
    - pkg-config
  commands:
    # check variables
    - test -f ${GWOLLUM_DATA}/V1-hrec-vsr2.gwf  # [unix]
    - test -f ${GWOLLUM_PIX}/gwollum.gif  # [unix]
    # check pkg-config
    - pkg-config --print-errors --exact-version {{ version }} {{ name }}

about:
  home: https://virgo.docs.ligo.org/virgoapp/{{ name }}/
  doc_url: https://virgo.docs.ligo.org/virgoapp/{{ name }}/
  dev_url: https://git.ligo.org/virgo/virgoapp/{{ name }}.git
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Tools for gravitational-wave analyses
  description: |
    The GWOLLUM package contains a set of software tools designed to perform
    GW analyses.  Most of the code source is written with the C++ language
    and it also heavily relies on the CERN ROOT libraries (also C++).

extra:
  recipe-maintainers:
    - duncanmmacleod
    - rhyspoulton
