{% set name = "gwollum" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.ligo.org/virgo/virgoapp/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 53c5b38d856ad55656068235a8e755f22a285124f9a7bd13495ce8e3f9345134
  patches:
    # use C++17 standard (required to link against ROOT>=6.14)
    - c++17.patch
    # update links
    - gsl-no-cblas.patch

build:
  error_overdepending: true
  error_overlinking: true
  number: 3
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("gwollum", max_pin="x.x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.9.0
    - make  # [unix]
    - pkg-config  # [unix]
  host:
    - fftw
    - gsl
    - hdf5
    - libframel >=8.40.5
    - root_base
    - root-binaries
  run:
    - fftw
    - gsl
    - hdf5
    - libframel
    - root_base
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  requires:
    - pkg-config
  commands:
    # sanity check
    - echo -e "1 2 3\n4 5 6" > triggers.txt
    - TxtToTree triggers.txt triggers a/I:b/I:c/I
    # check pkg-config
    - test "$(pkg-config --print-errors --modversion gwollum)" == "${PKG_VERSION}"  # [unix]

about:
  home: https://virgo.docs.ligo.org/virgoapp/{{ name }}/
  doc_url: https://virgo.docs.ligo.org/virgoapp/{{ name }}/
  dev_url: https://git.ligo.org/virgo/virgoapp/{{ name }}.git
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Tools for gravitational-wave analyses
  description: |
    The GWOLLUM package contains a set of software tools designed to perform
    GW analyses.  Most of the code source is written with the C++ language
    and it also heavily relies on the CERN ROOT libraries (also C++).

extra:
  recipe-maintainers:
    - duncanmmacleod
