schema_version: 1

context:
  name: gwollum
  version: 4.2.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://git.ligo.org/virgo/virgoapp/${{ name }}/-/archive/${{ version }}/${{ name }}-${{ version }}.tar.gz
  sha256: 7507afd34a53cc167612f869bba37967bfa9d76bf4b5b88f65ac52acf501fe98
  patches:
    # fix https://git.ligo.org/virgo/virgoapp/GWOLLUM/-/issues/59
    - cmakelists-version.patch
    # add missing TMath.h include for TMath::Min/Max
    - tmath-include.patch

build:
  number: 1
  skip: win

requirements:
  run_exports:
    - ${{ pin_subpackage("gwollum", upper_bound="x") }}
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake >=3.12.0
    - if: unix
      then: make
    - if: unix
      then: pkg-config
  host:
    - fftw
    - hdf5
    - libframel 8.42.*
    - root_base
    - root_cxx_standard

tests:
  - requirements:
      run:
        - pkg-config
    script:
      - if: unix
        then: test -f ${GWOLLUM_DATA}/V1-hrec-vsr2.gwf
      - if: unix
        then: test -f ${GWOLLUM_PIX}/gwollum.gif
      # run test executables
      - if: unix
        then: for gwltest in ${PREFIX}/sbin/gwl-test-*; do ${gwltest}; done
      - pkg-config --print-errors --exact-version ${{ version }} ${{ name }}

about:
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tools for gravitational-wave analyses
  description: |
    The GWOLLUM package contains a set of software tools designed to perform
    GW analyses.  Most of the code source is written with the C++ language
    and it also heavily relies on the CERN ROOT libraries (also C++).
  homepage: https://virgo.docs.ligo.org/virgoapp/${{ name }}/
  repository: https://git.ligo.org/virgo/virgoapp/${{ name }}.git
  documentation: https://virgo.docs.ligo.org/virgoapp/${{ name }}/

extra:
  recipe-maintainers:
    - duncanmmacleod
    - FlorentRobinet
